auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_entries_limit_per_query: 5000

chunk_store_config:
  max_look_back_period: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

ruler_storage:
  backend: local
  local:
    directory: /loki/rules

analytics:
  reporting_enabled: false

# Log stream labels configuration
stream_selector:
  - labels:
      - app
      - environment
      - component

# Alert rules for logs
alerting_rules:
  - name: high_error_rate
    rules:
      - alert: HighErrorRate
        expr: |
          sum(rate({app="pustu"} |= "error" [5m])) by (component)
          > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate in {{ $labels.component }}
          description: Error rate is above 10 per second

      - alert: APIErrorSpike
        expr: |
          sum(rate({app="pustu", component="api"} |= "error" [5m])) by (endpoint)
          > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: API error spike on {{ $labels.endpoint }}
          description: API errors have increased significantly

      - alert: DatabaseErrors
        expr: |
          sum(rate({app="pustu", component="database"} |= "error" [5m]))
          > 2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Database errors detected
          description: Database is experiencing errors

      - alert: QueueProcessingErrors
        expr: |
          sum(rate({app="pustu", component="queue"} |= "error" [5m]))
          > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Queue processing errors detected
          description: Queue system is experiencing errors

      - alert: AuthenticationFailures
        expr: |
          sum(rate({app="pustu", component="auth"} |= "failed" [5m]))
          > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate of authentication failures
          description: Multiple authentication failures detected

# Scrape configs for various log sources
scrape_configs:
  - job_name: pustu_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pustu_logs
          app: pustu
          environment: production
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            component: component
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          component:

  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          app: pustu
          environment: production
    pipeline_stages:
      - match:
          selector: '{job="system_logs"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<level>\w+) (?P<message>.*)'
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'
            - labels:
                level:

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          app: pustu
          environment: production
    pipeline_stages:
      - match:
          selector: '{job="nginx_logs"}'
          stages:
            - regex:
                expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<timestamp>[^\]]*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
            - timestamp:
                source: timestamp
                format: '02/Jan/2006:15:04:05 -0700'
            - labels:
                status:
                method:
